# Generated by Django 6.0.6 on 2026-07-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('method', models.CharField(choices=[('genre_favorit', 'Genre Favorit'), ('user_baru', 'User Baru (Cold Start)'), ('rating_sekali', 'Rating Satu Kali'), ('top_rated', 'Top Rated')], max_length=20)),
                ('score', models.FloatField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='movies.movie')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user_id', 'movie', 'method')},
            },
        ),
    ]
